export const translations = {
  pl: {
    submissions: "Zgłoszenia",
    instruction: "Instrukcja",
    staff: "Personel",
    timetable: "Plan lekcji",
    tasks: "Zadania",
    contact: "Kontakt",
    searchPlaceholder: "Szukaj",
    signIn: "Zaloguj się",
    signOut: "Wyloguj się",
    csi: "CSI",
    newSubmissions: "Nowe zgłoszenia",
    name: "Imię i Nazwisko",
    phone: "Telefon",
    fromEmail: "Adres e-mail nadawcy",
    toEmail: "Adres e-mail odbiorcy",
    location: "Lokalizacja",
    warsaw: "Warszawa",
    selectLocation: "Wybierz lokalizację",
    reportContent: "Treść zgłoszenia",
    visible: "Widoczny",
    send: "Wyślij",
    youSend: "Wysłano",
    youReceive: "Otrzymano",
    close: "Zamknij",
    systemsCenter: "Centrum Systemów Informatycznych",
    adress: "Ul. Dewajtis 5, 01-815 Warszawa",
    number: "Tel.: +48 22 561 89 21",
    room: "Stary Gmach, pok. 001",
    uksw: " Uniwersytet Kardynała Stefana Wyszyńskiego w Warszawie",
    ukswPhone: "Tel. centrala 22 561 88 00",
    login: "Logowanie",
    loginBTN: "Zaloguj się",
    forgotPassword: "Zapomniałeś hasła?",
    registre: "Nie masz konta? Zarejestruj",
    password: "Hasło",
    adressMail: "Adres e-mail",
    showPassword: "Pokaż hasło",
    alertLogin: "Login lub hasło jest niepoprawne!",
    registreName: "Imię",
    registreSurname: "Nazwisko",
    alreadyHaveAccount: "Już masz konta? Zaloguj się",
    registrationTitle: "Rejestracja",
    signUP: "Zarejestruj",
    role: "Twoja rola",
    roles: ["", "Student", "Pracownik", "Admin", "Serwisant"],
    timeRemaining: "Pozostały czas:",
    incsrtuctionReset:
      "Wprowadź swój token resetowania i nowe hasło, aby zresetować hasło:",
    resetPassword: "Zresetuj hasło",
    backToLogin: "Powrót do logowania",
    tokenExpired: "Token wygasł. Proszę o nowy.",
    instructionLogin:
      "Proszę wpisać swój login, a my wyślemy Ci hasło na Twój adres e-mail",
    reset: "Resetowanie",
    resetToken: "Zresetuj token",
    newPassword: "Nowe Hasło",
    infoAboutCSI: "Informacja o lokalizacjach CSI",
    active: "Czynne",
    floorDewajtis: "Piętro -1",
    floorWoycickiego: "Parter",
    time: "Pn-Pt: 7:30–15:30",
    seeOntheMap: "Zobacz na mapie",
    more:"Więcej",
    building:"bud",
    dewajtisAdress:" ul. Dewajtis 5, Stary Gmach pok. 1 ",
    woycickiegoAdress:" ul. Wóycickiego 1/3, bud. 21 pok. 024 "
  },
  en: {
    submissions: "Submissions",
    instruction: "Instruction",
    staff: "Staff",
    timetable: "Timetable",
    tasks: "Tasks",
    contact: "Contact",
    searchPlaceholder: "Search",
    signIn: "Sign in",
    signOut: "Sign out",
    csi: "CSI",
    newSubmissions: "New Submission",
    name: "Name and Surname",
    phone: "Phone",
    fromEmail: "From Email",
    toEmail: "To Email",
    location: "Location",
    warsaw: "Warszawa",
    selectLocation: "Select a location",
    reportContent: "Report Content",
    send: "Send",
    youSend: "You send",
    youReceive: "You receive",
    visible: "Visible",
    close: "Close",
    roles: ["", "Student", "Employee", "Admin", "Serviceman"],
    systemsCenter: "IT Systems Center",
    adress: "Street Dewajtis 5, 01-815 Warsaw",
    number: "Phone: +48 22 561 89 21",
    room: "Old Building, room 1st",
    uksw: "Cardinal Stefan Wyszyński University in Warsaw",
    ukswPhone: "Central phone 22 561 88 00",
    login: "Sign IN",
    loginBTN: "Sign IN",
    forgotPassword: "Forgot password?",
    registre: " Don't have an account? Sign Up",
    password: "Password",
    adressMail: "Email Address",
    showPassword: "Show password",
    alertLogin: "Wrong login or password!",
    registreName: "First Name",
    registreSurname: "Last Name",
    alreadyHaveAccount: "Already have an account? Sign in",
    registrationTitle: "Sign Up",
    signUP: "Sign Up",
    role: "You role",
    timeRemaining: "Time Remaining:",
    incsrtuctionReset:
      "Enter your reset token and new password to reset your password:",
    resetPassword: "Reset Password",
    backToLogin: "Back to login",
    tokenExpired: "The token has expired. Please request a new one.",
    instructionLogin:
      "Please write your login, and we will send you the password to your email",
    reset: "Reset",
    resetToken: "Reset Token",
    newPassword: "New Password",
    infoAboutCSI: "Information about CSI locations",
    active: "Active",
    floorDewajtis: "Floor -1",
    floorWoycickiego: "Ground floor",
    time: "Mn-Fr: 7:30–15:30",
    seeOntheMap: "See on the map",
    more:"More",
    building:"building.",
    dewajtisAdress:" st. Dewajtis 5, Stary Gmach room 1",
    woycickiegoAdress:" st. Wóycickiego 1/3, building 21 rooms 024"
  },
};
